title: "suprsvn"
url: "http://0nly.me"
author: "suprsvn"
email: "suprsvn@gmail.com"
description: "Shut up and then make it."

auto: false
source: .
paginate: 5
paginate_files:
 - index.html

permalink: /:year/:month/:title

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
